### ISSUE TITLE
不能在vc20 里编译通过 ImGui::Text(u8"UTF-8 字体测试");

### ISSUE THREAD

**Issue by imdjs** [opencodewin/imgui#5]
您好:
    我尝试编译你的代码demo,但不能通过编译(官方的imgui demo可以通过编译,但无法显示中文) ,似乎是因为参数 const char8_t[] 类型无法 转换成 const char* 类型. 不知你怎么解决这个问题?我使用的是vs 2022编译器.

[imgui.jpg](https://postimg.cc/sB0d4hd4)

**Comment by DickyQi** [comment]
sorry for responding late, we try to fixed imgui demo build on msvc(demo only), using "\x" plus utf8 hex code. we recommend using clang+MSVS to build project, because Microsoft c++ compiler isn't support C++11 well, also Windows support utf8 code method  is weird. It is still has issue if we need to build our internal icon-sets. if you need to display utf8(such as Chinese character), you also need build internal Chinese fonts into your project, or loading extra ttf font my coding.
我们尝试将demo中的utf8字符串编译问题修复了一下，方法就是用转意符，但是否能显示中文还需要您将中文字体加载（我们提供内建中文字体，也可以用外部ttf字体，显式代码加载）。在Windows中处理utf8字符串本身比较复杂（尤其是文件系统）。我们建议编译器的选择是clang/gcc(微软的c/c++编译器对C++11/c99的支持都有些问题）。
